// Curated 作文金句 (essay golden sentences), organized by theme:
// 描寫 (descriptive), 抒情 (lyrical/emotional), 論說 (argumentative/expository).
// `keyPhrase` is an exact substring of `sentence` used to build the
// fill-in-the-blank practice question (sentence.split(keyPhrase)).
// `scenario` is a short writing situation used for the scenario-match question.
window.App = window.App || {};
window.App.Content = window.App.Content || {};

(function () {
  const ESSAY_ITEMS = [
    // ---- 描寫 (Descriptive) ----
    {
      id: "sunset-palette",
      theme: "描寫",
      level: "p5",
      sentence: "夕陽緩緩沉落，把天邊染成一片橙紅，像是打翻了畫家的顏料盤。",
      keyPhrase: "像是打翻了畫家的顏料盤",
      usage: "用來描寫黃昏景色，以比喻手法（打翻顏料盤）令畫面更生動。",
      scenario: "想描寫黃昏時天空的顏色",
    },
    {
      id: "bright-eyes",
      theme: "描寫",
      level: "p5",
      sentence: "他一雙炯炯有神的眼睛，彷彿能看透人心。",
      keyPhrase: "炯炯有神",
      usage: "用來描寫人物眼神，突出角色機智或銳利的性格。",
      scenario: "想描寫一個聰明機警的人物",
    },
    {
      id: "spring-breeze",
      theme: "描寫",
      level: "p5",
      sentence: "春風輕輕拂過臉頰，帶來陣陣泥土和青草的芳香。",
      keyPhrase: "泥土和青草的芳香",
      usage: "用來描寫春天的氣息，透過觸覺與嗅覺增添畫面感。",
      scenario: "想描寫春天來臨的感覺",
    },
    {
      id: "rain-pearls",
      theme: "描寫",
      level: "p6",
      sentence: "雨點像斷了線的珍珠，噼哩啪啦地打在窗戶上。",
      keyPhrase: "像斷了線的珍珠",
      usage: "用比喻手法描寫雨勢，令文字更形象化。",
      scenario: "想描寫下大雨的情景",
    },
    {
      id: "bustling-market",
      theme: "描寫",
      level: "p6",
      sentence: "市集裏人聲鼎沸，叫賣聲、討價還價聲此起彼落，熱鬧非凡。",
      keyPhrase: "人聲鼎沸",
      usage: "用來描寫熱鬧的場面，善用四字詞增加氣氛。",
      scenario: "想描寫熱鬧的市場或節日場面",
    },
    {
      id: "nervous-heartbeat",
      theme: "描寫",
      level: "s1",
      sentence: "他的心跳如擂鼓一般，手心也不禁滲出冷汗。",
      keyPhrase: "如擂鼓一般",
      usage: "透過比喻和身體反應描寫緊張的心情，令讀者感同身受。",
      scenario: "想描寫角色感到十分緊張的時刻",
    },
    {
      id: "winter-snow",
      theme: "描寫",
      level: "p5",
      sentence: "雪花像一群群白色的蝴蝶，輕輕飄落在大地上，為世界披上一層潔白的外衣。",
      keyPhrase: "像一群群白色的蝴蝶",
      usage: "用來描寫下雪的景象，以比喻手法令畫面更輕盈動人。",
      scenario: "想描寫冬天下雪的情景",
    },
    {
      id: "autumn-leaves",
      theme: "描寫",
      level: "p5",
      sentence: "秋風一吹，滿樹金黃的葉子便紛紛飄落，像一群蝴蝶在空中翩翩起舞。",
      keyPhrase: "像一群蝴蝶在空中翩翩起舞",
      usage: "用來描寫秋天落葉紛飛的景象，比喻生動。",
      scenario: "想描寫秋天樹葉飄落的情景",
    },
    {
      id: "ocean-view",
      theme: "描寫",
      level: "p6",
      sentence: "大海一望無際，波浪一層層湧上岸邊，彷彿在訴說永不停息的故事。",
      keyPhrase: "彷彿在訴說永不停息的故事",
      usage: "用擬人手法描寫大海壯闊而富有生命力的一面。",
      scenario: "想描寫遼闊的大海景色",
    },
    {
      id: "playground-joy",
      theme: "描寫",
      level: "p5",
      sentence: "操場上傳來陣陣歡笑聲，同學們追逐嬉戲的身影，為寧靜的校園增添了無限生氣。",
      keyPhrase: "為寧靜的校園增添了無限生氣",
      usage: "用來描寫熱鬧的校園生活場面。",
      scenario: "想描寫小息時操場上熱鬧的情景",
    },
    {
      id: "quiet-night",
      theme: "描寫",
      level: "p6",
      sentence: "夜深了，四周靜得只剩下風吹樹葉的沙沙聲，彷彿全世界都已經沉沉睡去。",
      keyPhrase: "彷彿全世界都已經沉沉睡去",
      usage: "用擬人手法描寫深夜的寧靜氣氛。",
      scenario: "想描寫深夜萬籟俱寂的情景",
    },
    {
      id: "warm-smile",
      theme: "描寫",
      level: "p5",
      sentence: "她嘴角微微上揚，露出兩個淺淺的酒渦，笑容像陽光一樣温暖人心。",
      keyPhrase: "笑容像陽光一樣温暖人心",
      usage: "用比喻手法描寫人物親切温暖的笑容。",
      scenario: "想描寫一個笑容親切温暖的人物",
    },
    {
      id: "storm-wind",
      theme: "描寫",
      level: "p6",
      sentence: "狂風怒吼，暴雨傾盆而下，樹枝被吹得東搖西擺，彷彿隨時都會被連根拔起。",
      keyPhrase: "彷彿隨時都會被連根拔起",
      usage: "用誇張手法描寫狂風暴雨的猛烈程度。",
      scenario: "想描寫狂風暴雨的惡劣天氣",
    },
    {
      id: "elderly-face",
      theme: "描寫",
      level: "p6",
      sentence: "爺爺滿頭銀髮，臉上的皺紋像一道道歲月的痕跡，記錄着他一生的辛勞。",
      keyPhrase: "像一道道歲月的痕跡",
      usage: "用比喻手法描寫年長者飽經風霜的外貌。",
      scenario: "想描寫一位年邁長者的外貌",
    },
    {
      id: "busy-city",
      theme: "描寫",
      level: "s1",
      sentence: "高樓大廈鱗次櫛比，車水馬龍的街道上，人們行色匆匆，展現大都市的繁華與急促節奏。",
      keyPhrase: "展現大都市的繁華與急促節奏",
      usage: "運用四字詞描寫繁忙都市的景象，增加文句的節奏感。",
      scenario: "想描寫繁忙擁擠的城市街景",
    },
    {
      id: "festival-fireworks",
      theme: "描寫",
      level: "p6",
      sentence: "絢麗的煙花在夜空中綻放，一朵接一朵，把漆黑的天幕點綴得如同繁星閃爍。",
      keyPhrase: "把漆黑的天幕點綴得如同繁星閃爍",
      usage: "用比喻手法描寫煙花璀璨奪目的景象。",
      scenario: "想描寫節日夜晚煙花綻放的美麗畫面",
    },
    {
      id: "library-mood",
      theme: "描寫",
      level: "p6",
      sentence: "圖書館裏安靜得連翻書的聲音都清晰可聞，同學們埋首書海，沉醉在知識的世界裏。",
      keyPhrase: "沉醉在知識的世界裏",
      usage: "用來描寫圖書館專注閱讀的寧靜氣氛。",
      scenario: "想描寫圖書館裏專心讀書的情景",
    },
    {
      id: "puppy-eyes",
      theme: "描寫",
      level: "p5",
      sentence: "小狗搖着尾巴，睜着水汪汪的大眼睛望着我，彷彿在懇求我陪牠玩耍。",
      keyPhrase: "彷彿在懇求我陪牠玩耍",
      usage: "用擬人手法描寫小狗可愛討好的神態。",
      scenario: "想描寫一隻活潑可愛的小狗",
    },
    {
      id: "mountain-dawn",
      theme: "描寫",
      level: "s1",
      sentence: "晨曦初露，薄霧繚繞山間，鳥兒在枝頭婉轉歌唱，喚醒了沉睡的大地。",
      keyPhrase: "喚醒了沉睡的大地",
      usage: "用擬人手法描寫山間清晨甦醒的景象。",
      scenario: "想描寫山間清晨寧靜清新的景色",
    },
    {
      id: "exam-nerves",
      theme: "描寫",
      level: "s1",
      sentence: "距離考試只剩下最後五分鐘，他的手心不斷冒汗，心跳聲彷彿蓋過了周圍所有的聲音。",
      keyPhrase: "心跳聲彷彿蓋過了周圍所有的聲音",
      usage: "用誇張手法描寫考試前極度緊張的心情。",
      scenario: "想描寫考試前忐忑不安的心情",
    },

    // ---- 抒情 (Lyrical / emotional) ----
    {
      id: "missing-family",
      theme: "抒情",
      level: "p6",
      sentence: "每當夜深人靜，思念便如潮水般湧上心頭，久久不能平復。",
      keyPhrase: "如潮水般湧上心頭",
      usage: "用來抒發對親人的思念之情，比喻思念如潮水，情感濃烈。",
      scenario: "想表達對遠方親人的思念",
    },
    {
      id: "parents-love",
      theme: "抒情",
      level: "p5",
      sentence: "父母的愛，就像一盞永不熄滅的燈，默默地照亮我前行的路。",
      keyPhrase: "永不熄滅的燈",
      usage: "用來抒發對父母養育之恩的感激，比喻父母之愛如明燈。",
      scenario: "想表達對父母的感激之情",
    },
    {
      id: "old-wine-friendship",
      theme: "抒情",
      level: "p5",
      sentence: "友誼就像一杯陳年老酒，時間愈久，愈是香醇。",
      keyPhrase: "一杯陳年老酒",
      usage: "用來抒發珍惜友情的感受，以比喻手法帶出友誼歷久彌新。",
      scenario: "想表達珍惜與朋友的情誼",
    },
    {
      id: "time-flies",
      theme: "抒情",
      level: "p6",
      sentence: "光陰似箭，轉眼間，兒時的回憶已變得模糊而遙遠。",
      keyPhrase: "光陰似箭",
      usage: "用來抒發對時光飛逝的感慨，帶出懷念過去的情懷。",
      scenario: "想表達對時間流逝、懷念過去的感慨",
    },
    {
      id: "gritting-teeth",
      theme: "抒情",
      level: "s1",
      sentence: "即使前路崎嶇，我也願意咬緊牙關，一步一步走下去。",
      keyPhrase: "咬緊牙關",
      usage: "用來抒發面對困難時堅毅不屈的決心。",
      scenario: "想表達面對逆境時堅持不放棄的心情",
    },
    {
      id: "hometown-longing",
      theme: "抒情",
      level: "s1",
      sentence: "無論走到多遠，家鄉的一草一木，始終牽動着我的心。",
      keyPhrase: "一草一木",
      usage: "用來抒發對家鄉的思念與眷戀之情。",
      scenario: "想表達對家鄉的懷念之情",
    },
    {
      id: "grateful-teacher",
      theme: "抒情",
      level: "p5",
      sentence: "老師的教誨如春雨般滋潤我的心田，讓我在知識的道路上茁壯成長。",
      keyPhrase: "如春雨般滋潤我的心田",
      usage: "用來抒發對老師教導之恩的感激。",
      scenario: "想表達對老師的感激之情",
    },
    {
      id: "cherish-present",
      theme: "抒情",
      level: "p6",
      sentence: "時光一去不復返，與其留戀過去、擔憂未來，不如好好珍惜眼前的每一刻。",
      keyPhrase: "不如好好珍惜眼前的每一刻",
      usage: "用來抒發珍惜當下、把握現在的人生體會。",
      scenario: "想表達要珍惜眼前時光的道理",
    },
    {
      id: "sibling-bond",
      theme: "抒情",
      level: "p6",
      sentence: "雖然我們時常爭吵，但血濃於水的手足之情，卻是任何事物都無法取代的。",
      keyPhrase: "任何事物都無法取代的",
      usage: "用來抒發兄弟姊妹之間深厚的情誼。",
      scenario: "想表達與兄弟姊妹之間珍貴的感情",
    },
    {
      id: "facing-setback",
      theme: "抒情",
      level: "p5",
      sentence: "跌倒了不要緊，重要的是能夠拍拍身上的塵土，重新站起來勇敢面對。",
      keyPhrase: "重新站起來勇敢面對",
      usage: "用來抒發面對挫折時應有的積極態度。",
      scenario: "想表達遇到挫折仍要堅強面對的心情",
    },
    {
      id: "childhood-album",
      theme: "抒情",
      level: "p6",
      sentence: "童年的回憶就像一本泛黃的相簿，每一頁都記錄着最單純、最快樂的時光。",
      keyPhrase: "記錄着最單純、最快樂的時光",
      usage: "用比喻手法抒發對童年美好回憶的懷念。",
      scenario: "想表達對童年時光的懷念之情",
    },
    {
      id: "parents-sacrifice",
      theme: "抒情",
      level: "s1",
      sentence: "父母含辛茹苦地養育我成長，這份恩情比山高，比海深，我畢生也難以報答。",
      keyPhrase: "比山高，比海深",
      usage: "用比喻手法抒發對父母養育之恩深厚的感激。",
      scenario: "想表達對父母養育之恩的深切感激",
    },
    {
      id: "farewell-sorrow",
      theme: "抒情",
      level: "s1",
      sentence: "車廂緩緩開動，望着窗外漸漸遠去的身影，離愁別緒湧上心頭，久久不能平復。",
      keyPhrase: "離愁別緒湧上心頭",
      usage: "用來抒發與親人朋友離別時依依不捨的心情。",
      scenario: "想表達與親友離別時難捨難分的感受",
    },
    {
      id: "chasing-dreams",
      theme: "抒情",
      level: "p6",
      sentence: "即使前方困難重重，我仍願意懷着一顆熾熱的心，堅持追逐屬於自己的夢想。",
      keyPhrase: "堅持追逐屬於自己的夢想",
      usage: "用來抒發堅持追夢、永不放棄的決心。",
      scenario: "想表達堅持夢想、勇敢追求目標的心志",
    },
    {
      id: "distant-friendship",
      theme: "抒情",
      level: "p6",
      sentence: "雖然我們相隔千里，但這份友誼卻沒有因為距離而變得疏遠，反而愈加珍貴。",
      keyPhrase: "反而愈加珍貴",
      usage: "用來抒發對遠方朋友深厚友誼的珍惜。",
      scenario: "想表達對遠方朋友的思念與珍惜",
    },
    {
      id: "nature-humility",
      theme: "抒情",
      level: "s1",
      sentence: "漫步在寧靜的樹林中，我感受到大自然的偉大，也體會到自己的渺小。",
      keyPhrase: "也體會到自己的渺小",
      usage: "用來抒發置身大自然時謙卑而感動的心情。",
      scenario: "想表達親近大自然時的感悟與體會",
    },
    {
      id: "school-farewell",
      theme: "抒情",
      level: "s1",
      sentence: "畢業在即，回望這幾年在校園裏度過的時光，心裏滿是不捨與感激。",
      keyPhrase: "心裏滿是不捨與感激",
      usage: "用來抒發即將畢業、離開母校時的複雜心情。",
      scenario: "想表達對母校依依不捨的畢業心情",
    },
    {
      id: "unyielding-spirit",
      theme: "抒情",
      level: "p6",
      sentence: "即使身處逆境，我也絕不輕言放棄，因為我深信，堅持到底就是勝利。",
      keyPhrase: "堅持到底就是勝利",
      usage: "用來抒發面對逆境時堅毅不屈的信念。",
      scenario: "想表達身處逆境仍堅持到底的決心",
    },
    {
      id: "life-journey",
      theme: "抒情",
      level: "s1",
      sentence: "生命就像一場旅程，重要的不是終點，而是沿途所見的風景與經歷。",
      keyPhrase: "而是沿途所見的風景與經歷",
      usage: "用比喻手法抒發對生命意義的體會。",
      scenario: "想表達對人生、生命意義的感悟",
    },
    {
      id: "quiet-support",
      theme: "抒情",
      level: "p6",
      sentence: "謝謝你在我最脆弱的時候，默默地陪伴在我身邊，給予我最溫暖的支持。",
      keyPhrase: "給予我最溫暖的支持",
      usage: "用來抒發對身邊人默默支持、陪伴的感激之情。",
      scenario: "想表達對在困難時陪伴自己的人的感激",
    },

    // ---- 論說 (Argumentative / expository) ----
    {
      id: "no-gain-without-effort",
      theme: "論說",
      level: "p6",
      sentence: "天下沒有不勞而獲的事，成功的背後，往往藏着不為人知的努力。",
      keyPhrase: "不勞而獲",
      usage: "用來論證勤奮努力與成功的關係，適合寫議論文的開首或總結。",
      scenario: "想論證「努力才能成功」這個道理",
    },
    {
      id: "drop-wears-stone",
      theme: "論說",
      level: "p6",
      sentence: "滴水能穿石，並非力量強大，而是憑着持之以恆的堅持。",
      keyPhrase: "滴水能穿石",
      usage: "用比喻論證堅持的重要性，說理清晰有力。",
      scenario: "想論證「堅持不懈」的重要",
    },
    {
      id: "teamwork-building",
      theme: "論說",
      level: "s1",
      sentence: "獨木難支大廈，只有團結合作，才能成就更大的事業。",
      keyPhrase: "獨木難支大廈",
      usage: "用來論證團結合作的重要性，常用於議論文中。",
      scenario: "想論證「團結合作」的重要性",
    },
    {
      id: "knowledge-ladder",
      theme: "論說",
      level: "p6",
      sentence: "知識是通往成功的階梯，唯有不斷學習，才能攀上更高的高峰。",
      keyPhrase: "通往成功的階梯",
      usage: "用比喻論證學習知識的重要，適合作文章結尾勉勵語。",
      scenario: "想論證「學習知識」對成功的重要性",
    },
    {
      id: "integrity-foundation",
      theme: "論說",
      level: "s1",
      sentence: "誠信是做人的根本，一旦失去，縱有千金，也難以挽回別人的信任。",
      keyPhrase: "做人的根本",
      usage: "用來論證誠信的重要性，適合議論文中舉例說理。",
      scenario: "想論證「誠信」的重要性",
    },
    {
      id: "courage-to-retry",
      theme: "論說",
      level: "s1",
      sentence: "失敗並不可怕，可怕的是失去了再次嘗試的勇氣。",
      keyPhrase: "再次嘗試的勇氣",
      usage: "用來論證面對失敗應有的正確態度，鼓勵人勇於再嘗試。",
      scenario: "想論證「正視失敗、勇於嘗試」的道理",
    },
    {
      id: "time-management",
      theme: "論說",
      level: "p6",
      sentence: "時間對每個人都是公平的，能否善用時間，往往決定了一個人成就的高低。",
      keyPhrase: "往往決定了一個人成就的高低",
      usage: "用來論證善用時間管理的重要性。",
      scenario: "想論證「善用時間」對成功的重要性",
    },
    {
      id: "value-of-reading",
      theme: "論說",
      level: "s1",
      sentence: "閱讀是最廉價的奢侈，只要翻開書本，就能與古今中外的智者對話。",
      keyPhrase: "就能與古今中外的智者對話",
      usage: "用比喻論證閱讀能拓寬視野、增長見識。",
      scenario: "想論證「閱讀」對個人成長的重要性",
    },
    {
      id: "importance-of-exercise",
      theme: "論說",
      level: "p6",
      sentence: "生命在於運動，唯有堅持鍛煉身體，才能擁有健康的體魄去追求理想。",
      keyPhrase: "才能擁有健康的體魄去追求理想",
      usage: "用來論證運動對身體健康的重要性。",
      scenario: "想論證「多做運動」的重要性",
    },
    {
      id: "politeness-value",
      theme: "論說",
      level: "p6",
      sentence: "禮貌是人與人之間最好的通行證，一句簡單的問候，往往能拉近彼此的距離。",
      keyPhrase: "往往能拉近彼此的距離",
      usage: "用比喻論證禮貌待人的重要性。",
      scenario: "想論證「禮貌待人」的重要性",
    },
    {
      id: "frugality-virtue",
      theme: "論說",
      level: "s1",
      sentence: "由儉入奢易，由奢入儉難，養成節儉的習慣，才能在順境與逆境中都游刃有餘。",
      keyPhrase: "才能在順境與逆境中都游刃有餘",
      usage: "引用古語論證節儉的重要性。",
      scenario: "想論證「節儉」這種美德的重要性",
    },
    {
      id: "value-of-innovation",
      theme: "論說",
      level: "s1",
      sentence: "墨守成規只會原地踏步，唯有勇於創新、突破框架，才能在時代的洪流中脫穎而出。",
      keyPhrase: "才能在時代的洪流中脫穎而出",
      usage: "用來論證創新思維的重要性，適合議論文提出論點時使用。",
      scenario: "想論證「勇於創新」的重要性",
    },
    {
      id: "tolerance-wisdom",
      theme: "論說",
      level: "s1",
      sentence: "能夠包容別人的過錯，不僅是一種修養，更是一種智慧，令人與人之間的相處更加和諧。",
      keyPhrase: "更是一種智慧",
      usage: "用來論證寬容待人的價值。",
      scenario: "想論證「寬容待人」的重要性",
    },
    {
      id: "environmental-duty",
      theme: "論說",
      level: "p6",
      sentence: "地球只有一個，保護環境並非一時之事，而是我們每一個人都應肩負的責任。",
      keyPhrase: "而是我們每一個人都應肩負的責任",
      usage: "用來論證環保是眾人共同責任，適合環保主題議論文。",
      scenario: "想論證「保護環境」是每個人的責任",
    },
    {
      id: "self-discipline",
      theme: "論說",
      level: "s1",
      sentence: "沒有天生的自律，只有後天培養的習慣；能夠自律的人，往往能夠掌握自己的人生。",
      keyPhrase: "往往能夠掌握自己的人生",
      usage: "用來論證自律對掌握人生的重要性。",
      scenario: "想論證「自律」對個人成長的重要性",
    },
    {
      id: "dream-and-action",
      theme: "論說",
      level: "s1",
      sentence: "光有夢想而不付諸行動，夢想終究只是空想；唯有腳踏實地，才能一步步走向成功。",
      keyPhrase: "唯有腳踏實地，才能一步步走向成功",
      usage: "用來論證實踐比空談夢想更重要。",
      scenario: "想論證「夢想需要行動配合」的道理",
    },
    {
      id: "humility-value",
      theme: "論說",
      level: "p6",
      sentence: "謙受益，滿招損，愈是有才能的人，愈應該保持謙遜的態度，才能不斷進步。",
      keyPhrase: "才能不斷進步",
      usage: "引用古語論證謙虛待人的重要性。",
      scenario: "想論證「謙虛」的重要性",
    },
    {
      id: "true-friendship",
      theme: "論說",
      level: "s1",
      sentence: "真正的朋友不是在你風光時錦上添花，而是在你失意時雪中送炭。",
      keyPhrase: "而是在你失意時雪中送炭",
      usage: "用對比手法論證真摯友誼的可貴。",
      scenario: "想論證「真摯友誼」的可貴之處",
    },
    {
      id: "meaning-of-courage",
      theme: "論說",
      level: "s1",
      sentence: "勇氣並非天不怕地不怕，而是明知會害怕，仍然選擇迎難而上。",
      keyPhrase: "仍然選擇迎難而上",
      usage: "用來論證勇氣的真正意義，適合論說文開首點題。",
      scenario: "想論證「勇氣」的真正意義",
    },
    {
      id: "contentment-happiness",
      theme: "論說",
      level: "p6",
      sentence: "懂得知足的人，即使生活簡樸，也能活得比誰都快樂富足。",
      keyPhrase: "也能活得比誰都快樂富足",
      usage: "用來論證知足常樂的人生態度。",
      scenario: "想論證「知足常樂」的道理",
    },
  ];

  const ESSAY_THEMES = ["描寫", "抒情", "論說"];
  const ESSAY_THEME_EMOJI = { 描寫: "🎨", 抒情: "💭", 論說: "💡" };
  const ESSAY_LEVEL_LABEL = { p5: "小五", p6: "小六", s1: "中一" };

  window.App.Content.ESSAY_ITEMS = ESSAY_ITEMS;
  window.App.Content.ESSAY_THEMES = ESSAY_THEMES;
  window.App.Content.ESSAY_THEME_EMOJI = ESSAY_THEME_EMOJI;
  window.App.Content.ESSAY_LEVEL_LABEL = ESSAY_LEVEL_LABEL;
})();
